### PR TITLE
Disallow uploading of new md5 checksummed files

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by praiskup** [comment]
Hi, thanks. Could we have opt-out option for this?

**Comment by praiskup** [comment]
(copr still uses md5)

**Comment by puiterwijk** [comment]
@praiskup Here you go. It currently defaults to allowing md5, and in a future release we should move it to default to disallowing md5.

**Comment by praiskup** [comment]
Thanks, looks good to me.

> in a future release we should move it to default to disallowing md5.

Agreed; that's why I was suggesting making it opt-out instead of opt-in.

**Comment by clime** [comment]
Thanks.

**Pull request merged**
