### PR TITLE
Dontaudit read all domains state.

### PR DESCRIPTION
**Pull request by wrabcak**

### CODE REVIEW

**Comment by clime** [comment]
Can you, please, describe difference between `domain_read_all_domains_state` and `domain_dontaudit_read_all_domains_state`?

**Comment by wrabcak** [comment]
domain_read_all_domains_state() macro will allow reading all process information in /proc for httpd_git_script_t, but domain_read_all_domains_state() don't allow it and AVCs won't be recorded in audit.log

**Comment by clime** [comment]
You mean that `domain_dontaudit_read_all_domains_state` won't allow it and don't audit it?

Are you sure this is not needed anywhere in the DistGit cgi scripts? I must admin I don't see a reason for `domain_read_all_domains_state` to be allowed but at the same time, I don't know the original reason why it was put there. Any further insight will be appreciated.

**Comment by wrabcak** [comment]
Yes, it won't be allowed and also it won't be recorded by audit daemon. 

httpd_git_script_t is trying to read process information in /proc/<pid>. Also you can see in comment in source code that author tried to dontaudit it not allowed it. This is reason why I created this PR.

**Comment by clime** [comment]
I guess i would prefer just removing both the rule and the comment altogether because it seems it is no longer needed.

**Comment by wrabcak** [comment]
Okay, If it's no longer needed, feel free to remove it.

**Comment by clime** [comment]
Cool, thanks for consulting this!

**Pull request closed without merging**
