### PR TITLE
disable network for Packit

### PR DESCRIPTION
**Pull request by xsuchy**

### CODE REVIEW

**Comment by xsuchy** [comment]
Because of https://github.com/packit/packit/issues/1821

**Comment by praiskup** [comment]
The change has no effect, right?  Because CI has not started failing.

**Comment by praiskup** [comment]
It actually looks like the network is disabled by default, see the [build log](https://download.copr.fedorainfracloud.org/results/packit/release-engineering-dist-git-59/epel-7-x86_64/05200633-dist-git/builder-live.log.gz) triggered by #60.

**Comment by xsuchy** [comment]
Hmm, but random recent job from dashboard:
https://dashboard.packit.dev/results/copr-builds/572257
has network enabled.  And related packit.yaml does not mention network at all.

**Comment by praiskup** [comment]
Seems like this is not needed.

**Pull request closed without merging**
