### PR TITLE
Move the dist-git-client code from Copr codebase

### PR DESCRIPTION
**Pull request by praiskup**

### CODE REVIEW

**Comment by FrostyX** [comment]
I am not doing the review of the code because it is an existing code from the Copr project. For the same reason, I'd ignore the failing linter. I was able to build Tito packages (test and production) for the distgit package but only test package for the client package. Don't forget to make an appropriate tag in the repository for the 1.0-1 version.

I like the suggested project structure, the only thing I'd like to see is `dist-git-client/README.md` with a short description of the client and mainly an example of how to configure and use it.

**Review by FrostyX — APPROVED** [review]

**Comment by praiskup** [comment]
Thank you!  _Agreed,_ I added a simple README.md file.  PTAL

**Comment by praiskup** [comment]
The `dist-git` Rawhide build failure is not related to this change, so I propose to fix it later, in #64.

**Review by FrostyX — APPROVED** [review]
Perfect, thank you very much.

**Comment by FrostyX** [comment]
I think this PR broke the images in the README. See "How Does It Work" and "Video Tutorial" sections here https://github.com/release-engineering/dist-git

On https://github.com/release-engineering/dist-git/tree/main/dist-git the "Video Tutorial" works but "How Does It Work" is broken too.

**Pull request merged**
