### PR TITLE
autotoolize and configuration as ini file

### PR DESCRIPTION
**Pull request by praiskup**
While I started looking at fixing pull request #9, I felt quite desperate from pathname handling in dist-git project.  Now the paths are set at one place (configure.ac or Makefile.am) and "configurable".

Both python and shell sources use ini-file for configuration, so $git_author is easily configurable.

This is not yet complete, but at least you can quick a look.

### CODE REVIEW

**Comment by praiskup** [comment]
@xsuchy @clime please take a look, thanks

**Comment by clime** [comment]
Why not simply keep the paths run-time configurable? Putting AUTHOR to the config file should have been a simple change. I would like to keep things simple until the package is actually working somewhere reliably. This seems to be way too complicated now.

**Comment by praiskup** [comment]
> Putting AUTHOR to the config file should have been a simple change.

Scripts must know where the config file is, and that's what this change solves.

> This seems to be way too complicated now.

Define now :).  But I can argue the change is really trivial, have a look how much of code was actually changed (if you don't count spec file, that was simplified).

So the larger part of this PR is build-system addition which should be there sooner or later anyways (at least IMO) ..   Of course you can count with my help with maintenance.

**Comment by praiskup** [comment]
I guess my comment was unintentionally edited, but I got it .. :)

**Comment by clime** [comment]
@praiskup: Err, true, I am very sorry for that :(. Glad you understood and thank you!

**Comment by praiskup** [comment]
> Yeah but they did know it: '/etc/dist-git/dist-git.conf'

Yup, but each of them needs to hard-code the path;  so I'll try to split if you really think it makes sense (/me not being fan of pull-requests like #10 if we can be compare).

**Pull request closed without merging**
