### PR TITLE
mention source-git

### PR DESCRIPTION
**Pull request by xsuchy**

### CODE REVIEW

**Comment by clime** [comment]
I am not sure, does it use this project internally?

**Comment by xsuchy** [comment]
It is intended to work on top of dist-git. It is in the same relation as Mock is to rpmbuild.

**Comment by clime** [comment]
Well, i meant if you can link me to specific place in code where this project is used...that would be great...if there is no such place, we can still merge this, of course ...

**Comment by xsuchy** [comment]
It is not used there. Just related.

**Pull request merged**
